#include "common.h"
#include "static/119280.h"

/*.data*/

/*01022510*/
_119280UnkStruct1 D_01022510[64] = {
    { 100, 20, 0, 15, 35 },
    { 101, 20, 1, 15, 35 },
    { 102, 20, 2, 15, 35 },
    { 103, 20, 3, 15, 35 },
    { 104, 20, 4, 15, 35 },
    { 105, 20, 5, 15, 35 },
    { 106, 20, 6, 15, 35 },
    { 107, 20, 7, 15, 35 },
    { 108, 20, 8, 15, 35 },
    { 109, 20, 9, 15, 35 },
    { 110, 20, 10, 15, 35 },
    { 111, 20, 11, 15, 35 },
    { 112, 20, 12, 15, 35 },
    { 113, 20, 13, 15, 35 },
    { 114, 20, 14, 15, 35 },
    { 115, 20, 15, 15, 35 },
    { 116, 20, 16, 15, 35 },
    { 117, 20, 17, 15, 35 },
    { 118, 20, 18, 15, 35 },
    { 119, 20, 19, 15, 35 },
    { 120, 20, 20, 15, 35 },
    { 121, 20, 21, 15, 35 },
    { 122, 20, 22, 15, 35 },
    { 123, 20, 23, 15, 35 },
    { 124, 20, 24, 15, 35 },
    { 125, 20, 25, 15, 35 },
    { 126, 20, 26, 15, 35 },
    { 127, 20, 27, 15, 35 },
    { 128, 20, 28, 15, 35 },
    { 129, 20, 29, 15, 35 },
    { 130, 20, 30, 15, 35 },
    { 131, 20, 31, 15, 35 },
    { 132, 20, 32, 15, 35 },
    { 133, 20, 33, 15, 35 },
    { 134, 20, 34, 15, 35 },
    { 135, 20, 35, 15, 35 },
    { 136, 20, 36, 15, 35 },
    { 137, 20, 37, 15, 35 },
    { 138, 20, 38, 15, 35 },
    { 139, 20, 39, 15, 35 },
    { 140, 20, 40, 15, 35 },
    { 141, 20, 41, 15, 35 },
    { 142, 20, 42, 15, 35 },
    { 143, 20, 43, 15, 35 },
    { 144, 20, 44, 15, 35 },
    { 145, 20, 45, 15, 35 },
    { 146, 20, 46, 15, 35 },
    { 147, 20, 47, 15, 35 },
    { 148, 20, 48, 15, 35 },
    { 149, 20, 49, 15, 35 },
    { 150, 20, 50, 15, 35 },
    { 151, 20, 51, 15, 35 },
    { 152, 20, 52, 15, 35 },
    { 153, 20, 53, 15, 35 },
    { 154, 20, 54, 15, 35 },
    { 155, 20, 55, 15, 35 },
    { 156, 20, 56, 15, 35 },
    { 157, 20, 57, 15, 35 },
    { 158, 20, 58, 15, 35 },
    { 159, 20, 59, 15, 35 },
    { 160, 20, 60, 15, 35 },
    { 161, 20, 61, 15, 35 },
    { 162, 20, 62, 15, 35 },
    { 163, 20, 63, 15, 35 },
};

/*01022790*/
u8 D_01022790[512] = {
    0xFF, 0xFE, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
};

/*01022990*/
ControlMapping gControlPreset[8] = {
#if defined(VERSION_US) || defined(VERSION_EU) || defined(VERSION_PROTO)
    {
        {
            "CONTROL STICK LEFT",
            "CONTROL STICK RIGHT",
            "TOP C BUTTON",
            "BOTTOM C BUTTON",
            "LEFT C BUTTON",
            "RIGHT C BUTTON",
            "CONTROL STICK DOWN",
            "CONTROL STICK UP",
            "R BUTTON",
            "Z BUTTON",
            "B BUTTON",
            "A+CONTROL STICK RIGHT",
            "A+CONTROL STICK LEFT",
            "A+CONTROL STICK DOWN",
            "A+CONTROL STICK UP",
            "A+Z",
        },
    },
    {
        {
            "CONTROL STICK LEFT",
            "CONTROL STICK RIGHT",
            "CONTROL PAD UP",
            "CONTROL PAD DOWN",
            "CONTROL PAD LEFT",
            "CONTROL PAD RIGHT",
            "CONTROL STICK DOWN",
            "CONTROL STICK UP",
            "L BUTTON",
            "Z BUTTON",
            "B BUTTON",
            "A+CONTROL STICK RIGHT",
            "A+CONTROL STICK LEFT",
            "A+CONTROL STICK DOWN",
            "A+CONTROL STICK UP",
            "A+Z",
        },
    },
    {
        {
            "CONTROL STICK LEFT",
            "CONTROL STICK RIGHT",
            "CONTROL STICK UP",
            "CONTROL STICK DOWN",
            "LEFT C BUTTON",
            "RIGHT C BUTTON",
            "BOTTOM C BUTTON",
            "TOP C BUTTON",
            "R BUTTON",
            "Z BUTTON",
            "B BUTTON",
            "A+CONTROL STICK RIGHT",
            "A+CONTROL STICK LEFT",
            "A+CONTROL STICK DOWN",
            "A+CONTROL STICK UP",
            "A+Z",
        },
    },
    {
        {
            "CONTROL STICK LEFT",
            "CONTROL STICK RIGHT",
            "CONTROL STICK UP",
            "CONTROL STICK DOWN",
            "CONTROL PAD LEFT",
            "CONTROL PAD RIGHT",
            "CONTROL PAD DOWN",
            "CONTROL PAD UP",
            "L BUTTON",
            "Z BUTTON",
            "B BUTTON",
            "A+CONTROL STICK RIGHT",
            "A+CONTROL STICK LEFT",
            "A+CONTROL STICK DOWN",
            "A+CONTROL STICK UP",
            "A+Z",
        },
    },
    {
        {
            "CONTROL STICK LEFT",
            "CONTROL STICK RIGHT",
            "TOP C BUTTON",
            "BOTTOM C BUTTON",
            "LEFT C BUTTON",
            "RIGHT C BUTTON",
            "CONTROL STICK DOWN",
            "CONTROL STICK UP",
            "R BUTTON",
            "Z BUTTON",
            "B BUTTON",
            "A BUTTON",
            "CONTROL PAD LEFT",
            "CONTROL PAD DOWN",
            "CONTROL PAD UP",
            "L BUTTON",
        },
    },
    {
        {
            "CONTROL STICK LEFT",
            "CONTROL STICK RIGHT",
            "CONTROL PAD UP",
            "CONTROL PAD DOWN",
            "CONTROL PAD LEFT",
            "CONTROL PAD RIGHT",
            "CONTROL STICK DOWN",
            "CONTROL STICK UP",
            "L BUTTON",
            "Z BUTTON",
            "B BUTTON",
            "A BUTTON",
            "LEFT C BUTTON",
            "BOTTOM C BUTTON",
            "TOP C BUTTON",
            "R BUTTON",
        },
    },
    {
        {
            "CONTROL STICK LEFT",
            "CONTROL STICK RIGHT",
            "CONTROL STICK UP",
            "CONTROL STICK DOWN",
            "LEFT C BUTTON",
            "RIGHT C BUTTON",
            "BOTTOM C BUTTON",
            "TOP C BUTTON",
            "R BUTTON",
            "Z BUTTON",
            "B BUTTON",
            "A BUTTON",
            "CONTROL PAD LEFT",
            "CONTROL PAD DOWN",
            "CONTROL PAD UP",
            "L BUTTON",
        },
    },
    {
        {
            "CONTROL STICK LEFT",
            "CONTROL STICK RIGHT",
            "CONTROL STICK UP",
            "CONTROL STICK DOWN",
            "CONTROL PAD LEFT",
            "CONTROL PAD RIGHT",
            "CONTROL PAD DOWN",
            "CONTROL PAD UP",
            "L BUTTON",
            "Z BUTTON",
            "B BUTTON",
            "A BUTTON",
            "LEFT C BUTTON",
            "BOTTOM C BUTTON",
            "TOP C BUTTON",
            "R BUTTON",
        },
    },
#elif VERSION_FR
    {
        {
            "LEVIER CTRL GAUCHE",
            "LEVIER CTRL DROITE",
            "BOUTON C HAUT",
            "BOUTON C BAS",
            "BOUTON C GAUCHE",
            "BOUTON C DROITE",
            "LEVIER CTRL BAS",
            "LEVIER CTRL HAUT",
            "BOUTON R",
            "BOUTON Z",
            "BOUTON B",
            "A+LEVIER CTRL DROITE",
            "A+LEVIER CTRL GAUCHE",
            "A+LEVIER CTRL BAS",
            "A+LEVIER CTRL HAUT",
            "A+Z",
        },
    },
    {
        {
            "LEVIER CTRL GAUCHE",
            "LEVIER CTRL DROITE",
            "BOUTON D HAUT",
            "BOUTON D BAS",
            "BOUTON D GAUCHE",
            "BOUTON D DROITE",
            "LEVIER CTRL BAS",
            "LEVIER CTRL HAUT",
            "BOUTON L",
            "BOUTON Z",
            "BOUTON B",
            "A+LEVIER CTRL DROITE",
            "A+LEVIER CTRL GAUCHE",
            "A+LEVIER CTRL BAS",
            "A+LEVIER CTRL HAUT",
            "A+Z",
        },
    },
    {
        {
            "LEVIER CTRL GAUCHE",
            "LEVIER CTRL DROITE",
            "LEVIER CTRL HAUT",
            "LEVIER CTRL BAS",
            "BOUTON C GAUCHE",
            "BOUTON C DROITE",
            "BOUTON C BAS",
            "BOUTON C HAUT",
            "BOUTON R",
            "BOUTON Z",
            "BOUTON B",
            "A+LEVIER CTRL DROITE",
            "A+LEVIER CTRL GAUCHE",
            "A+LEVIER CTRL BAS",
            "A+LEVIER CTRL HAUT",
            "A+Z",
        },
    },
    {
        {
            "LEVIER CTRL GAUCHE",
            "LEVIER CTRL DROITE",
            "LEVIER CTRL HAUT",
            "LEVIER CTRL BAS",
            "BOUTON D GAUCHE",
            "BOUTON D DROITE",
            "BOUTON D BAS",
            "BOUTON D HAUT",
            "BOUTON L",
            "BOUTON Z",
            "BOUTON B",
            "A+LEVIER CTRL DROITE",
            "A+LEVIER CTRL GAUCHE",
            "A+LEVIER CTRL BAS",
            "A+LEVIER CTRL HAUT",
            "A+Z",
        },
    },
    {
        {
            "LEVIER CTRL GAUCHE",
            "LEVIER CTRL DROITE",
            "BOUTON C HAUT",
            "BOUTON C BAS",
            "BOUTON C GAUCHE",
            "BOUTON C DROITE",
            "LEVIER CTRL BAS",
            "LEVIER CTRL HAUT",
            "BOUTON R",
            "BOUTON Z",
            "BOUTON B",
            "BOUTON A",
            "BOUTON D GAUCHE",
            "BOUTON D BAS",
            "BOUTON D HAUT",
            "BOUTON L",
        },
    },
    {
        {
            "LEVIER CTRL GAUCHE",
            "LEVIER CTRL DROITE",
            "BOUTON D HAUT",
            "BOUTON D BAS",
            "BOUTON D GAUCHE",
            "BOUTON D DROITE",
            "LEVIER CTRL BAS",
            "LEVIER CTRL HAUT",
            "BOUTON L",
            "BOUTON Z",
            "BOUTON B",
            "BOUTON A",
            "BOUTON C GAUCHE",
            "BOUTON C DROITE",
            "BOUTON C HAUT",
            "BOUTON R",
        },
    },
    {
        {
            "LEVIER CTRL GAUCHE",
            "LEVIER CTRL DROITE",
            "LEVIER CTRL HAUT",
            "LEVIER CTRL BAS",
            "BOUTON C GAUCHE",
            "BOUTON C DROITE",
            "BOUTON C BAS",
            "BOUTON C HAUT",
            "BOUTON R",
            "BOUTON Z",
            "BOUTON B",
            "BOUTON A",
            "BOUTON D GAUCHE",
            "BOUTON D BAS",
            "BOUTON D HAUT",
            "BOUTON L",
        },
    },
    {
        {
            "LEVIER CTRL GAUCHE",
            "LEVIER CTRL DROITE",
            "LEVIER CTRL HAUT",
            "LEVIER CTRL BAS",
            "BOUTON D GAUCHE",
            "BOUTON D DROITE",
            "BOUTON D BAS",
            "BOUTON D HAUT",
            "BOUTON L",
            "BOUTON Z",
            "BOUTON B",
            "BOUTON A",
            "BOUTON C GAUCHE",
            "BOUTON C BAS",
            "BOUTON C HAUT",
            "BOUTON R",
        },
    },
#endif
};
